import "@/app/globals.css";
import UIProvider from "@/shared/providers/next-ui-provider";
import QueryProvider from "@/shared/providers/query-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UIProvider>
          <QueryProvider>{children}</QueryProvider>
        </UIProvider>
      </body>
    </html>
  );
}
