import "@/app/globals.css";
import UIProvider from "@/processes/providers/next-ui-provider";
import QueryProvider from "@/processes/providers/query-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <UIProvider> {children}</UIProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
