import "@/app/globals.css";
import I18nProvider from "@/shared/providers/i18-provider";
import UIProvider from "@/shared/providers/next-ui-provider";
import QueryProvider from "@/shared/providers/query-provider";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Kuku",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <UIProvider>
          <QueryProvider>
            <I18nProvider>{children}</I18nProvider>
          </QueryProvider>
        </UIProvider>
      </body>
    </html>
  );
}
