import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kuku | Search",
  description: "Generated by create next app",
};

const SearchLayout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default SearchLayout;
